// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uirlwmgtiihljkylovnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpcmx3bWd0aWlobGpreWxvdm5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTgwMzgsImV4cCI6MjA2ODQ5NDAzOH0.d-m0SpsrvF0-fS70C2e9b-TXMURrI7fXAtuTi729tOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});